# Generated by Django 4.2.6 on 2023-11-22 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tacher_single_models',
        ),
        migrations.RenameField(
            model_name='teacher_models',
            old_name='first_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='teacher_models',
            old_name='last_name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='facebook_field',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='gmail_field',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='teacher img'),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='instaqram_field',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='twitter_field',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
