# Generated by Django 4.2.6 on 2023-11-22 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_delete_tacher_single_models_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_models',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
