# Generated by Django 4.2.6 on 2023-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_models_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_models',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='teacher img'),
        ),
    ]
