# Generated by Django 4.2.6 on 2023-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_models_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_video_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='teacher video')),
            ],
        ),
    ]
