# Generated by Django 4.2.6 on 2023-12-02 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_video_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_video_models',
            name='courses_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_video_models',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_video_models',
            name='title2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
