# Generated by Django 4.2.6 on 2023-12-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_video_models_courses_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_video_models',
            name='courses_name',
        ),
    ]
