# Generated by Django 4.2.6 on 2023-12-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_teacher_video_models_courses_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_models',
            name='gmail_field',
        ),
    ]
