# Generated by Django 4.2.6 on 2023-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_teacher_models_gmail_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_models',
            name='description_az',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='description_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='fullname_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher_models',
            name='fullname_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
