# Generated by Django 4.2.6 on 2023-12-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_teacher_models_description_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_models',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='teacher_models',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='teacher_models',
            name='fullname_az',
        ),
        migrations.RemoveField(
            model_name='teacher_models',
            name='fullname_en',
        ),
    ]
