# Generated by Django 4.2.6 on 2023-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery_models',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='galery_models',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='galery_models',
            name='last_name',
        ),
        migrations.AddField(
            model_name='galery_models',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='gallery img'),
        ),
    ]
