# Generated by Django 4.2.6 on 2023-11-26 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_galery_models_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery_models',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
