# Generated by Django 4.2.6 on 2023-11-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_video_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='news video')),
            ],
        ),
        migrations.DeleteModel(
            name='news_single_models',
        ),
        migrations.RenameField(
            model_name='news_models',
            old_name='first_name',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='news_models',
            old_name='instrument',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='news_models',
            old_name='last_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='news_models',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='news img'),
        ),
    ]
