# Generated by Django 4.2.6 on 2023-11-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_video_models_delete_news_single_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_models',
            name='Description',
            field=models.CharField(max_length=100000),
        ),
    ]
