# Generated by Django 4.2.6 on 2023-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_models_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_models',
            name='Description',
            field=models.TextField(max_length=100000),
        ),
    ]
