# Generated by Django 4.2.6 on 2023-11-23 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events_single_models',
        ),
        migrations.RenameField(
            model_name='events_models',
            old_name='first_name',
            new_name='history',
        ),
        migrations.RemoveField(
            model_name='events_models',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='events_models',
            name='last_name',
        ),
        migrations.AddField(
            model_name='events_models',
            name='Description',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events_models',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='events img'),
        ),
        migrations.AddField(
            model_name='events_models',
            name='location',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
