# Generated by Django 4.2.6 on 2023-11-23 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_events_single_models_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_models',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
