# Generated by Django 4.2.6 on 2023-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_models_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_models',
            name='created_at',
        ),
    ]
