# Generated by Django 4.2.6 on 2023-11-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_events_models_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_video_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(blank=True, null=True, upload_to='video', verbose_name='events video')),
            ],
        ),
    ]
