# Generated by Django 4.2.6 on 2023-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_video_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='course video')),
            ],
        ),
    ]
