# Generated by Django 4.2.6 on 2023-11-17 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_models',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact_models',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='contact_models',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact_models',
            name='Email',
            field=models.CharField(default=django.utils.timezone.now, help_text='max character limit 255', max_length=255, verbose_name='bura emailinizi daxil edin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_models',
            name='Message',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='movzunu daxil edin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_models',
            name='Subject',
            field=models.CharField(default=django.utils.timezone.now, help_text='max character limit 255', max_length=255, verbose_name='movzu hakkinda ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_models',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, help_text='max character limit 255', max_length=255, verbose_name='bura adınızı daxil edin'),
            preserve_default=False,
        ),
    ]
