# Generated by Django 4.2.6 on 2023-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_models_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('Message', models.TextField(verbose_name='your user description')),
                ('Email', models.EmailField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
                ('Subject', models.CharField(help_text='max character limit 255', max_length=255, verbose_name='Title of the your core')),
            ],
            options={
                'verbose_name': 'corepost',
                'verbose_name_plural': 'All contact fomrs',
            },
        ),
        migrations.DeleteModel(
            name='contact_models',
        ),
    ]
