# Generated by Django 4.2.6 on 2023-11-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactinfo_delete_contact_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactinfo',
            new_name='contact_forms_models',
        ),
    ]
